<!-- Required meta tags -->
<meta charset="utf-8">
<link rel="apple-touch-icon" sizes="76x76" href="/assets/img/favicon.png">
<link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon.png">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="/assets/css/bootstrap-theme.min.css">

<!-- jQuery UI -->
<link rel="stylesheet" href="/assets/css/jquery-ui.min.css">

<!-- jTable -->
<link rel="stylesheet" href="/assets/js/plugins/jtable.2.4.0/themes/basic/jtable_basic.css">
<link rel="stylesheet" href="/assets/css/jtable-custom.css">

<!-- Chosen -->
<link rel="stylesheet" href="/assets/css/chosen/chosen.css">
<link rel="stylesheet" href="/assets/css/chosen/bootstrap-chosen.css">

<!-- Select 2 -->
<link rel="stylesheet" href="/assets/css/select2/select2.css?v2">

<!-- Context Menu -->
<link rel="stylesheet" href="/assets/css/contextmenu/jquery.contextMenu.min.css">

<!-- Pivottable -->
<link rel="stylesheet" href="/assets/css/pivottable/pivot.min.css">

<!-- Custom CSS -->
<link rel="stylesheet" href="/assets/css/custom.css?v4">

<!-- Fonts awesome -->
<!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous"> -->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

<title>Mi Fútbol</title>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-92893104-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-92893104-6');
</script>

