<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="/assets/js/core/jquery-3.3.1.min.js"></script>
<script src="/assets/js/core/popper.min.js"></script>
<script src="/assets/js/core/bootstrap.min.js"></script>

<!-- jQuery UI JS -->
<script src="/assets/js/plugins/jquery-ui.min.js"></script>

<!-- Bootstrap notify -->
<script src="/assets/js/plugins/bootstrap-notify.js"></script>

<!-- jTable -->
<script src="/assets/js/plugins/jtable.2.4.0/jquery.jtable.js?v=9"></script>
<script src="/assets/js/plugins/jtable.2.4.0/localization/jquery.jtable.es.js"></script>

<!-- Chosen -->
<script src="/assets/js/plugins/chosen/chosen.jquery.js"></script>

<!-- Select 2 -->
<script src="/assets/js/plugins/select2/select2.js"></script>

<!-- Context Menu -->
<script src="/assets/js/plugins/contextmenu/jquery.contextMenu.min.js"></script>
<script src="/assets/js/plugins/contextmenu/jquery.ui.position.js"></script>

<!-- Block UI -->
<script src="/assets/js/plugins/jquery.blockUI.js"></script>

<!-- Pivottable -->
<script src="/assets/js/plugins/pivottable/pivot.min.js"></script>
<script src="/assets/js/plugins/pivottable/pivot.es.min.js"></script>

<!-- Custom JavaScript -->
<script src="/assets/js/plugins/custom.js?v9"></script>