<nav class="navbar navbar-expand-lg navbar-danger bg-danger">
	<a class="navbar-brand text-light" href="#">
		<img src="/assets/img/favicon.png" width="30" height="30" class="d-inline-block align-top" alt="">
		Yo Ladrillo
	</a>
	
	<?php if (isset($username_session)) : ?>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto"></ul>
		<form class="form-inline my-2 my-lg-0 mr-3">
			<ul class="navbar-nav mr-auto">
				
				<?php if (isset($company_session)) : ?>
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-building"></i> <?= $company_session ?>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="/login/companies/selection"><i class="fa fa-retweet"></i> Elegir otra Compañía</a>
					</div>
				</li>
				<?php endif; ?>
				
				<li class="nav-item dropdown active">
					<a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user-check"></i> <?= $username_session ?>
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="#"><i class="fa fa-edit"></i> Editar perfil</a>
						<div class="dropdown-divider"></div>
						<a class="dropdown-item" href="#" name="btnLogout"><i class="fa fa-times"></i> Cerrar sesión</a>
					</div>
				</li>
			</ul>
		</form>
	</div>
	<?php endif; ?>
</nav>