<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" style="z-index:10;background-color:#FF6347 !important">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#toolbarSupportedContent" aria-controls="toolbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="toolbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link text-light" href="#" id="btn-toolbar-save">
					<i class="fa fa-save"></i> Guardar
				</a>
			</li>
			<li class="nav-item active">
				<a class="nav-link text-light" href="#" role="button" aria-haspopup="true" aria-expanded="false">
					<i class="fa fa-undo"></i> Volver
				</a>
			</li>
		</ul>
	</div>
</nav>