<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-6">
						<div class="card mt-3">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-file-invoice-dollar"></i> Cuentas Bancarias</b></span>
							</div>
							<div class="card-body">
							    <div class="row">
							        <div class="col">
							            <div name="table-content"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				// table-content
				$('div[name="table-content"]').jtable({
					title: ' ',
					columnSelectable: false,
					showCommandButtons: false,
					actions: {
						listAction: '/banks_accounts/read',
						deleteAction: '/banks_accounts/remove',
						updateAction: '/banks_accounts/update',
						createAction: '/banks_accounts/create'
					},
					fields: {
						id: {
							key: true,
							create: false,
							edit: false,
							list: false
						},
						number: {
							title: 'Número',
							width: '30%',
							inputClass: 'form-control',
						},
						alias: {
							title: 'Alias',
							width: '30%',
							inputClass: 'form-control',
						},
						bank_id: {
							title: 'Banco',
							width: '30%',
							options: '/banks/options',
							inputClass: 'form-control',
						},
						menu: {
							title: '',
							width: '10%',
							edit: false,
							create: false,
							display: function (data) {
								return '<span class="btn btn-light btn-sm" name="btn-table-context-menu" data-record-key="' + data.record.id + '"><i class="fa fa-ellipsis-v"></i></span>';
							},
						},
					},
					//Initialize validation logic when a form is created
					formCreated: function (event, data) {
						data.form.find('select[name="bank_id"]').select2({ width : '100%'});
						
						// # select2: resolve focus issue
    					if ($.ui && $.ui.dialog && $.ui.dialog.prototype._allowInteraction) {
    						var ui_dialog_interaction = $.ui.dialog.prototype._allowInteraction;
    						$.ui.dialog.prototype._allowInteraction = function(e) {
    							if ($(e.target).closest('.select2-dropdown').length) return true;
    							return ui_dialog_interaction.apply(this, arguments);
    						};
    					}
					},
				});
		 
				//Load list from server
				$('div[name="table-content"]').jtable('load');
				
				// Add Bootstrap style to jTable
				$.stdjTableBootstrapStyle();
				
				// Context Menu
				$.contextMenu({
					selector: 'span[name="btn-table-context-menu"]',
					trigger: 'left',
					items: {
						"edit": {
							name: '<span><i class="fa fa-edit"></i> Editar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showEditForm', $row);
								return true;
							},
						},
						"delete": {
							name: '<span><i class="fa fa-trash-alt"></i> Eliminar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showDeleteDialog', $row);
								return true;            
							}   
						},
					}
				});
				
			});
		</script>
	</body>
</html>