<!doctype html>
<html lang="en">
	<head>	
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar-login.phtml') ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-sm-7 col-md-5 col-lg-4 mx-auto">
						<div class="card mt-3">
							<div class="card-header d-flex justify-content-between">
								<span><strong>Recuperar contraseña</strong></span>
								<span name="currentDateText"></span>
							</div>
							<div class="card-body">
								<form>
									<div class="form-group">
										<label>Ingresá tu usuarios o e-mail:</label>
										<input type="text" class="form-control" name="username" placeholder="Usuario o email" required>
									</div>
								</form>
							</div>
							<div class="card-footer d-flex justify-content-between">
								<a class="pt-2" href="/login"><i class="fa fa-arrow-left"></i> Volver</a>
								<button type="submit" class="btn btn-outline-primary"><i class="fas fa-check"></i> Enviar e-mail</button>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){				
				$('button[type="submit"]').on('click', function(e) {
					e.preventDefault();
					$.ajax({
						method: 'POST',
						url: '/login',
						data: $('form').serialize(),
						success: function(data, textStatus, jqXHR) {
							if (data.status == 'ok') {
								window.location.replace('/login/clubs_selection');
							}
							else if (data.status == 'error') {
								$.stdShowMessage({
									icon: 'fa fa-exclamation-triangle',
									message: 'Usuario y/o contraseña incorrectos',
									type: 'info'
								});
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				});
			});
		</script>
	</body>
</html>