<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-<?= count($projects) * 4 ?>">
						<div class="card mt-3">
							<div class="card-header">
								<span><b><i class="fa fa-home"></i> Seleccionar Proyecto</b></span>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-12">
										<div class="card-group">
											
											<?php foreach($projects as $project) : ?>
											<div class="card">
												<div class="card-body">
													<div class="row">
														<div class="col-6">
															<p><?= trim($project->full_name) ?></p>
															<button
																class="btn btn-outline-primary"
																name="btn-select"
																data-value="<?= $project->id ?>">
																Seleccionar
															</button>
														</div>
														<div class="col-6">
															<img class="img-fluid rounded mx-auto d-block" src="<?= $project->photo->public_url ?>">
														</div>
													</div>
												</div>
											</div>
											<?php endforeach; ?>
											
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				$('button[name="btn-select"]').on('click', function(e){
					e.preventDefault();
					
					var project_id = $(this).attr('data-value');
					
					$.ajax({
						method: 'POST',
						url: '/login/projects/selected/' + project_id,
						success: function(data, textStatus, jqXHR) {
							if (data.status == 'ok') {
								window.location.replace('/exchange');
							}
							else if (data.status == 'error') {
								$.stdShowMessage({
									icon: 'fa fa-exclamation-triangle',
									message: 'Ups! Algo salió mal. <br>Vuelva a intentarlo más tarde.',
									type: 'info'
								});
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},	
					});
				});
				
			});
		</script>
	</body>
</html>