<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
		
		<style>
			textarea {
				border: none;
				overflow: auto;
				outline: none;
				-webkit-box-shadow: none;
				-moz-box-shadow: none;
				box-shadow: none;
				resize: none; /*remove the resize handle on the bottom right*/
				font: 15px Courier New;
				width: 100%;
				height: 1000px;
			}
		</style>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?php $customers_enabled 			= (isset($customers) and count($customers) > 0); ?>
		<?php $salesDocsTypes_enabled		= (isset($salesDocsTypes) and count($salesDocsTypes) > 0); ?>
		<?php $collectionsDocsTypes_enabled	= (isset($collectionsDocsTypes) and count($collectionsDocsTypes) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded" style="height:100%">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-list-ul"></i> Listado de Ventas</b></span>
							</div>
							<div class="card-body">
								
								<div class="row">
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Clientes:</label>
											<br>
											<label <?= !$customers_enabled ? '' : 'class="d-none" ' ?>name="customers-label"><i class="fa fa-exclamation-triangle"></i> No hay clientes disponibles!</label>
											<select class="form-control<?= $customers_enabled ? '' : ' d-none' ?>" name="customers-select" multiple="multiple">
											<?php if ($customers_enabled) : ?>
											<?php foreach($customers as $customer) : ?>
												<option value="<?= $customer->id ?>">
													<?= $customer->unique_code . ' | ' . $customer->business_name ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comp. de Ventas:</label>
											<div class="form-check form-check-inline">
												<input class="form-check-input" type="checkbox" name="sales-docs-types-check-nothing">
												<label class="form-check-label">Ninguno</label>
											</div>
											<br>
											<label <?= !$salesDocsTypes_enabled ? '' : 'class="d-none" ' ?>name="sales-docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $salesDocsTypes_enabled ? '' : ' d-none' ?>" name="sales-docs-types-select" multiple="multiple">
											<?php if ($salesDocsTypes_enabled) : ?>
											<?php foreach($salesDocsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
									
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comp. de Cobros:</label>
											<div class="form-check form-check-inline">
												<input class="form-check-input" type="checkbox" name="collections-docs-types-check-nothing">
												<label class="form-check-label">Ninguno</label>
											</div>
											<br>
											<label <?= !$collectionsDocsTypes_enabled ? '' : 'class="d-none" ' ?>name="collections-docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $collectionsDocsTypes_enabled ? '' : ' d-none' ?>" name="collections-docs-types-select" multiple="multiple">
											<?php if ($collectionsDocsTypes_enabled) : ?>
											<?php foreach($collectionsDocsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								</div>
								
								<div class="row">
							        <div class="col">
										<div class="btn btn-outline-primary" name="btn-report"><i class="fa fa-report"></i> Generar Reporte</div>
									<div>
								</div>
								
								<hr>
								
							    <div class="row mt-3">
							        <div class="col">
							            <div id="pivot"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				if ( !$('select[name="customers-select"]').hasClass('d-none') )
					$('select[name="customers-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="sales-docs-types-select"]').hasClass('d-none') )
					$('select[name="sales-docs-types-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="collections-docs-types-select"]').hasClass('d-none') )
					$('select[name="collections-docs-types-select"]').select2({ width: '100%' });
				
				// click on report
				$('div[name="btn-report"]').on('click', function(e) {
					e.preventDefault();
					
					var salesDocsCodes = ['x'];
					if ( !$('input[name="sales-docs-types-check-nothing"]').prop('checked') ) {
						salesDocsCodes = $('select[name="sales-docs-types-select"]').val();
					}
					
					var collectionsDocsCodes = ['x'];
					if ( !$('input[name="collections-docs-types-check-nothing"]').prop('checked') ) {
						collectionsDocsCodes = $('select[name="collections-docs-types-select"]').val();
					}
					
					// pivot
					$.ajax({
						method: 'POST',
						url: '/sales/pivot',
						data: { 
							customers_ids : 			$('select[name="customers-select"]').val(),
							sales_docs_codes : 			salesDocsCodes,
							collections_docs_codes : 	collectionsDocsCodes,
						},
						success: function(data, textStatus, jqXHR) {
							
							if (data.Result == 'OK')
							{
								$("#pivot").pivotUI(data.Records);
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
    				
				});
				
				// checkboxes
				$('input[name="sales-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="sales-docs-types-select"]').prop("disabled", checked);
				});
				
				$('input[name="collections-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="collections-docs-types-select"]').prop("disabled", checked);
				});
				
			});
		</script>
	</body>
</html>