<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded" style="height:100%">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-bars"></i> Historial</b></span>
							</div>
							<div class="card-body">
							    <div class="row mt-3">
							        <div class="col">
							            <div id="pivot"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				refreshPivot();

				function refreshPivot()
				{
					// pivot
					$.ajax({
						method: 'POST',
						url: '/matches/pivot',
						success: function(data, textStatus, jqXHR)
						{
							if (data.Result == 'OK')
							{
								$("#pivot").pivotUI(data.Records);
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				}
			});
		</script>
	</body>
</html>