<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded" style="height:100%">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-bars"></i> Historial</b></span>
							</div>
							<div class="card-body">
							    <div class="row mt-3">
							        <div class="col">
							            <div id="pivot"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				if ( !$('select[name="customers-select"]').hasClass('d-none') )
					$('select[name="customers-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="sales-docs-types-select"]').hasClass('d-none') )
					$('select[name="sales-docs-types-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="collections-docs-types-select"]').hasClass('d-none') )
					$('select[name="collections-docs-types-select"]').select2({ width: '100%' });
				
				// click on report
				$('div[name="btn-report"]').on('click', function(e) {
					e.preventDefault();
					
					var salesDocsCodes = ['x'];
					if ( !$('input[name="sales-docs-types-check-nothing"]').prop('checked') ) {
						salesDocsCodes = $('select[name="sales-docs-types-select"]').val();
					}
					
					var collectionsDocsCodes = ['x'];
					if ( !$('input[name="collections-docs-types-check-nothing"]').prop('checked') ) {
						collectionsDocsCodes = $('select[name="collections-docs-types-select"]').val();
					}
					
					// pivot
					$.ajax({
						method: 'POST',
						url: '/sales/pivot',
						data: { 
							customers_ids : 			$('select[name="customers-select"]').val(),
							sales_docs_codes : 			salesDocsCodes,
							collections_docs_codes : 	collectionsDocsCodes,
						},
						success: function(data, textStatus, jqXHR) {
							
							if (data.Result == 'OK')
							{
								$("#pivot").pivotUI(data.Records);
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
    				
				});
				
				// checkboxes
				$('input[name="sales-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="sales-docs-types-select"]').prop("disabled", checked);
				});
				
				$('input[name="collections-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="collections-docs-types-select"]').prop("disabled", checked);
				});
				
			});
		</script>
	</body>
</html>