<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-12 p-0">
						<div class="card card-no-rounded">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-search"></i> Buscar Resultados</b></span>
							</div>
							<div class="card-body">
							    <div class="row">
							        <div class="col">
							            <div name="table-content"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function()
			{
				// table-content
				$('div[name="table-content"]').jtable({
					title: ' ',
					columnSelectable: false,
					showCommandButtons: false,
					paging: true,
					pageList: 'normal',
					pageSize: 10,
					actions: {
						listAction: '/matches/read',
						deleteAction: '/matches/remove',
					},
					fields: {
						id: {
							key: true,
							create: false,
							edit: false,
							list: false
						},
						menu: {
							title: '',
							width: '5%',
							edit: false,
							create: false,
							display: function (data) {
								return '<span class="btn btn-light btn-sm" name="btn-table-context-menu" data-record-key="' + data.record.id + '"><i class="fa fa-ellipsis-v"></i></span>';
							},
						},
						dated_at: {
							title: 'Fecha',
							width: '10%',
							display: function(data) {
								var options = {
									timeZone: 'UTC',
									timeZoneName: 'GMT-03:00'
								};
								return new Date(data.record.dated_at).toLocaleDateString('es-AR', options);
							}
						},
						white_result: {
							title: 'Blancos',
							width: '10%',
						},
						black_result: {
							title: 'Negros',
							width: '10%',
						},
					}
				});
		 
				//Load list from server
				$('div[name="table-content"]').jtable('load');
				
				// Add Bootstrap style to jTable
				$.stdjTableBootstrapStyle();
				
				// Context Menu
				$.contextMenu({
					selector: 'span[name="btn-table-context-menu"]',
					trigger: 'left',
					items: {
						"edit": {
							name: '<span><i class="fa fa-edit"></i> Editar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								window.location.href = '/matches/' + opt.$trigger.attr('data-record-key');
								return false;
							},
						},
						"delete": {
							name: '<span><i class="fa fa-trash-alt"></i> Eliminar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showDeleteDialog', $row);
								return true;            
							}   
						},
					}
				});
				
			});
		</script>
	</body>
</html>