<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
		
		<style>
			textarea {
				border: none;
				overflow: auto;
				outline: none;
				-webkit-box-shadow: none;
				-moz-box-shadow: none;
				box-shadow: none;
				resize: none; /*remove the resize handle on the bottom right*/
				font: 15px Courier New;
				width: 100%;
				height: 1000px;
			}
		</style>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?php $suppliers_enabled 			= (isset($suppliers) and count($suppliers) > 0); ?>
		<?php $purchasesDocsTypes_enabled	= (isset($purchasesDocsTypes) and count($purchasesDocsTypes) > 0); ?>
		<?php $paymentsDocsTypes_enabled	= (isset($paymentsDocsTypes) and count($paymentsDocsTypes) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12 p-0">
						<div class="card card-no-rounded" style="height:100%">
							<div class="card-header d-flex justify-content-between">
								<span><b><i class="fa fa-list-ul"></i> Listado de Compras</b></span>
							</div>
							<div class="card-body">
								
								<div class="row">
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Proveedores:</label>
											<br>
											<label <?= !$suppliers_enabled ? '' : 'class="d-none" ' ?>name="suppliers-label"><i class="fa fa-exclamation-triangle"></i> No hay proveedores disponibles!</label>
											<select class="form-control<?= $suppliers_enabled ? '' : ' d-none' ?>" name="suppliers-select" multiple="multiple">
											<?php if ($suppliers_enabled) : ?>
											<?php foreach($suppliers as $supplier) : ?>
												<option value="<?= $supplier->id ?>">
													<?= $supplier->unique_code . ' | ' . $supplier->business_name ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comp. de Compras:</label>
											<div class="form-check form-check-inline">
												<input class="form-check-input" type="checkbox" name="purchases-docs-types-check-nothing">
												<label class="form-check-label">Ninguno</label>
											</div>
											<br>
											<label <?= !$purchasesDocsTypes_enabled ? '' : 'class="d-none" ' ?>name="purchases-docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $purchasesDocsTypes_enabled ? '' : ' d-none' ?>" name="purchases-docs-types-select" multiple="multiple">
											<?php if ($purchasesDocsTypes_enabled) : ?>
											<?php foreach($purchasesDocsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
									
									<div class="col-lg-4 col-md-6">
										<div class="form-group">
											<label class="font-weight-bold">Comp. de Pagos:</label>
											<div class="form-check form-check-inline">
												<input class="form-check-input" type="checkbox" name="payments-docs-types-check-nothing">
												<label class="form-check-label">Ninguno</label>
											</div>
											<br>
											<label <?= !$paymentsDocsTypes_enabled ? '' : 'class="d-none" ' ?>name="payments-docs-types-label"><i class="fa fa-exclamation-triangle"></i> No hay documentos disponibles!</label>
											<select class="form-control<?= $paymentsDocsTypes_enabled ? '' : ' d-none' ?>" name="payments-docs-types-select" multiple="multiple">
											<?php if ($paymentsDocsTypes_enabled) : ?>
											<?php foreach($paymentsDocsTypes as $documentType) : ?>
												<option
													value="<?= $documentType->unique_code ?>">
													<?= trim($documentType->description) ?>
												</option>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								</div>
								
								<div class="row">
							        <div class="col">
										<div class="btn btn-outline-primary" name="btn-report"><i class="fa fa-report"></i> Generar Reporte</div>
									<div>
								</div>
								
								<hr>
									
							    <div class="row mt-3">
							        <div class="col">
							            <textarea name="report-content"></textarea>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				if ( !$('select[name="suppliers-select"]').hasClass('d-none') )
					$('select[name="suppliers-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="purchases-docs-types-select"]').hasClass('d-none') )
					$('select[name="purchases-docs-types-select"]').select2({ width: '100%' });
				
				if ( !$('select[name="payments-docs-types-select"]').hasClass('d-none') )
					$('select[name="payments-docs-types-select"]').select2({ width: '100%' });
				
				// click on report
				$('div[name="btn-report"]').on('click', function(e) {
					e.preventDefault();
					
					var purchasesDocsCodes = ['x'];
					if ( !$('input[name="purchases-docs-types-check-nothing"]').prop('checked') ) {
						purchasesDocsCodes = $('select[name="purchases-docs-types-select"]').val();
					}
					
					var paymentsDocsCodes = ['x'];
					if ( !$('input[name="payments-docs-types-check-nothing"]').prop('checked') ) {
						paymentsDocsCodes = $('select[name="payments-docs-types-select"]').val();
					}
					
					$.ajax({
						method: 'POST',
						url: '/purchases/report',
						data: { 
							suppliers_ids : 		$('select[name="suppliers-select"]').val(),
							purchases_docs_codes : 	purchasesDocsCodes,
							payments_docs_codes : 	paymentsDocsCodes,
						},
						success: function(data, textStatus, jqXHR) {
							
							if (data.Result == 'OK') {
								/*var content = "";
								data.Records.forEach(function(record){
									content += record.value;
								});*/
								$('textarea[name="report-content"]').html(data.Records);
							}
							else {
								alert('error');
							}
						},
						error: function(jqXHR, textStatus, errorThrown) {
							console.warn(jqXHR.responseText);
						},
					});
				});
				
				// checkboxes
				$('input[name="purchases-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="purchases-docs-types-select"]').prop("disabled", checked);
				});
				
				$('input[name="payments-docs-types-check-nothing"]').on('change', function(e) {
					var checked = $(this).prop('checked');
					$('select[name="payments-docs-types-select"]').prop("disabled", checked);
				});
				
			});
		</script>
	</body>
</html>