<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-12">
						<div class="card mt-3">
							<div class="card-header">
								<span><b><i class="fa fa-calendar-alt"></i> Reservación de Canchas</b></span>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col">
										<i class="fa fa-search"></i> <label class="card-title font-weight-bold">Búscar disponibilidad:</label>
									</div>
								</div>
								<div class="row">
							        <div class="col-lg-3 col-md-4">
										<input type="datetime-local" class="form-control" name="datetimeSchedule" />
									</div>
							        <div class="col">
										<span class="btn btn-outline-primary" name="btn-search"><i class="fa fa-search"></i> Buscar</span>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
			
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				
				
			});
		</script>
	</body>
</html>