<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<?php $tournaments_enabled 	= (isset($tournaments) and count($tournaments) > 0); ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-5">
						<div class="card mt-3">
							<div class="card-header">
								<span><b><i class="fa fa-layer-group"></i> Asociación de Categorías</b></span>
							</div>
							<div class="card-body">
							    <div class="row">
									<div class="col-lg-7">
										<div class="form-group">
											<label class="font-weight-bold">Torneo:</label>
											<br>
											<label <?= !$tournaments_enabled ? '' : 'class="d-none" ' ?>name="tournaments-label"><i class="fa fa-exclamation-triangle"></i> No hay torneos disponibles!</label>
											<select class="form-control<?= $tournaments_enabled ? '' : ' d-none' ?>" name="tournaments-select">
											<?php if($tournaments_enabled) : ?>
											<?php foreach($tournaments as $tournament) : ?>
												<?= '<option value="' . $tournament->id . '"' . ((isset($tournament_id) and $tournament->id == $tournament_id) ? ' selected' : ''). '>' . $tournament->description . '</option>'; ?>
											<?php endforeach; ?>
											<?php endif; ?>
											</select>
										</div>
									</div>
								</div>
								
								<div class="row mt-4">
									<div class="col-lg-12">
										<div <?= $tournaments_enabled ? '' : 'class="d-none" ' ?>name="table-content"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				// table-content
				$('div[name="table-content"]').jtable({
					title: ' ',
					columnSelectable: false,
					showCommandButtons: false,
					actions: {
						listAction: function (postData, jtParams) {
							return $.Deferred(function ($dfd) {
								var tournament_id = $('select[name="tournaments-select"]').val();
								
								$.ajax({
									url: '/tournaments_categories/read/' + tournament_id,
									type: 'POST',
									dataType: 'json',
									data: postData,
									success: function (data) {
										$dfd.resolve(data);
									},
									error: function () {
										$dfd.reject();
									}
								});
							});
						},
						createAction: function (postData, jtParams) {
							return $.Deferred(function ($dfd) {
								var tournament_id = $('select[name="tournaments-select"]').val();
								
								$.ajax({
									url: '/tournaments_categories/create/' + tournament_id,
									type: 'POST',
									dataType: 'json',
									data: postData,
									success: function (data) {
										$dfd.resolve(data);
									},
									error: function () {
										$dfd.reject();
									}
								});
							});
						},
						updateAction: '/tournaments_categories/update',
						deleteAction: '/tournaments_categories/remove',
					},
					fields: {
						id: {
							key: true,
							create: false,
							edit: false,
							list: false
						},
						tournament_id: {
							create: false,
							edit: false,
							list: false
						},
						category_id: {
							title: 'Categoría',
							width: '40%',
							options: '/categories/options',
							inputClass: 'form-control',
						},
						enrollment: {
							title: 'Inscripción',
							width: '50%',
							create: false,
							edit: false,
							display: function(data) {
								return '<a href="/enrollments/' + data.record.tournament_id + '/' + data.record.category_id + '"><i class="fa fa-clipboard-list"></i> Inscribir jugadores</a>';
							},
						},
						menu: {
							title: '',
							width: '10%',
							edit: false,
							create: false,
							display: function (data) {
								return '<span class="btn btn-light btn-sm" name="btn-table-context-menu" data-record-key="' + data.record.id + '" data-record-tournament-id="' + data.record.tournament_id + '" data-record-category-id="' + data.record.category_id + '"><i class="fa fa-ellipsis-v"></i></span>';
							},
						},
					},
				});
		 
				//Load list from server
				$('div[name="table-content"]').jtable('load');
				
				// Add Bootstrap style to jTable
				$.stdjTableBootstrapStyle();
				
				// on tournaments index change
				$('select[name="tournaments-select"]').on('change', function(e) {
					//Load list from server
					$('div[name="table-content"]').jtable('load');
				});
				
				// Context Menu
				$.contextMenu({
					selector: 'span[name="btn-table-context-menu"]',
					trigger: 'left',
					items: {
						"matches": {
							name: '<span><i class="fa fa-sitemap"></i> Ver partidos</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e){
								window.location.href = '/matches/' + opt.$trigger.attr('data-record-tournament-id') + '/' + opt.$trigger.attr('data-record-category-id');
								return false;             
							}   
						},
						separator1: "-",
						"edit": {
							name: '<span><i class="fa fa-edit"></i> Editar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showEditForm', $row);
								return true;
							},
						},
						"delete": {
							name: '<span><i class="fa fa-trash-alt"></i> Eliminar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showDeleteDialog', $row);
								return true;            
							}   
						},
					}
				});
				
			});
		</script>
	</body>
</html>