<!doctype html>
<html lang="en">
	<head>
		<?= $this->fetch('/partials/header.phtml') ?>
	</head>
	<body>
		<?= $this->fetch('/partials/navbar.phtml', $navbar) ?>
		
		<div class="container-fluid">
			<div class="content">
				<div class="row">
					<div class="col-lg-7">
						<div class="card mt-3">
							<div class="card-header">
								<span><b><i class="fa fa-sliders-h"></i> Administración de Torneos</b></span>
							</div>
							<div class="card-body">
								<div class="row">
									<div class="col-lg-12">
										<div class="form-check form-check-inline">
											<input class="form-check-input" type="checkbox" id="show-all-check">
											<label class="form-check-label" for="show-all-check"><b>Mostrar inactivos</b></label>
										</div>
									</div>
								</div>
							
							    <div class="row mt-4">
							        <div class="col">
							            <div name="table-content"></div>
							        </div>
							    </div>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</div>
			
		<?= $this->fetch('/partials/libs.phtml') ?>
		
		<!-- Optional JavaScript -->
		<script>
			$(function(){
				
				// table-content
				$('div[name="table-content"]').jtable({
					title: ' ',
					columnSelectable: false,
					showCommandButtons: false,
					actions: {
						listAction: '/tournaments/read',
						deleteAction: '/tournaments/remove',
						updateAction: '/tournaments/update',
						createAction: '/tournaments/create'
					},
					fields: {
						id: {
							key: true,
							create: false,
							edit: false,
							list: false
						},
						description: {
							title: 'Nombre',
							width: '30%',
							inputClass: 'form-control',
						},
						is_active: {
							title: 'Estado',
							width: '20%',
							type: 'checkbox',
							values: { '0' : 'Inactivo', '1' : 'Activo'},
							display: function(data) {
								if (data.record.is_active == '1') {
									return '<i class="text-success fa fa-check"></i>';
								}
								return '<i class="text-dark fa fa-times"></i>';
							},
						},
						tournament_type_id: {
							title: 'Tipo',
							width: '20%',
							options: '/tournaments_types/options',
							list: false,
							inputClass: 'form-control',
						},
						start_date: {
							title: 'Fecha',
							width: '20%',
							type: 'date',
							displayFormat: 'yy-mm-dd',
							listClass: 'd-none d-lg-table-cell',
							inputClass: 'form-control',
						},
						apply_ranking: {
							title: '¿Suma para el ranking?',
							width: '20%',
							options: { 'NA' : 'No definido', 'YES' : 'Sí', 'NO' : 'No'},
							listClass: 'd-none d-lg-table-cell',
							inputClass: 'form-control',
						},
						is_visible: {
							title: '¿Visible?',
							width: '10%',
							type: 'checkbox',
							values: { '1' : 'Sí', '0' : 'No'},
							listClass: 'd-none d-lg-table-cell',
							display: function(data) {
								if (data.record.is_visible == '1') {
									return '<i class="text-dark fa fa-eye"></i>';
								}
								return '<i class="text-dark fa fa-eye-slash"></i>';
							},
						},
						menu: {
							title: '',
							width: '10%',
							edit: false,
							create: false,
							display: function (data) {
								return '<span class="btn btn-light btn-sm" name="btn-table-context-menu" data-record-key="' + data.record.id + '"><i class="fa fa-ellipsis-v"></i></span>';
							},
						},
					},
				});
		 
				//Load list from server
				$('#show-all-check').on('change', function(e) {
					$('div[name="table-content"]').jtable('load', { showAll : ($(this).prop('checked') ? 1 : 0) });
				});
				$('#show-all-check').change();
				
				// Add Bootstrap style to jTable
				$.stdjTableBootstrapStyle();
				
				// Context Menu
				$.contextMenu({
					selector: 'span[name="btn-table-context-menu"]',
					trigger: 'left',
					items: {
						"categories": {
							name: '<span><i class="fa fa-sort-alpha-up"></i> Asociar categorías</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e){
								window.location.href = '/tournaments_categories/' + opt.$trigger.attr('data-record-key');
								return false;             
							}   
						},
						separator1: "-",
						"edit": {
							name: '<span><i class="fa fa-edit"></i> Editar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showEditForm', $row);
								return true;
							},
						},
						"delete": {
							name: '<span><i class="fa fa-trash-alt"></i> Eliminar</span>',
							isHtmlName: true,
							callback: function(itemKey, opt, e) {
								$row = $('tr.jtable-data-row[data-record-key="' + opt.$trigger.attr('data-record-key') + '"]');
								$('div[name="table-content"]').jtable('showDeleteDialog', $row);
								return true;            
							}   
						},
					}
				});
				
			});
		</script>
	</body>
</html>